version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: film_catalogue_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: film_catalogue
    ports:
      - "5432:5432"